SELECT PT.NAME AS PRODUCT_TYPE,
   AVG(case when R.DT = 1 then -R.SUM else R.SUM end) AS AVG_MOVEMENT
FROM RECORDS R
JOIN ACCOUNTS A ON R.ACC_REF = A.ID
JOIN PRODUCTS P ON A.PRODUCT_REF = P.ID
JOIN PRODUCT_TYPE PT ON P.PRODUCT_TYPE_ID = PT.ID
GROUP BY PT.NAME;


