SELECT DISTINCT C.*
FROM CLIENTS C
  JOIN PRODUCTS P ON C.ID = P.CLIENT_REF
WHERE P.PRODUCT_TYPE_ID = (SELECT ID FROM PRODUCT_TYPE WHERE NAME = 'КРЕДИТ')
AND NOT EXISTS (
  SELECT 1
  FROM RECORDS R
  JOIN ACCOUNTS A ON R.ACC_REF = A.ID
  WHERE A.PRODUCT_REF = P.ID AND R.DT = 1
  GROUP BY A.ID
  HAVING SUM(R.SUM) < (SELECT MAX(R2.SUM) FROM RECORDS R2 JOIN ACCOUNTS A2 ON R2.ACC_REF = A2.ID WHERE A2.PRODUCT_REF = P.ID)
);



