SELECT C.NAME AS CLIENT_NAME,
   R.OPER_DATE,
   SUM(CASE WHEN R.DT = 1 THEN -R.SUM ELSE R.SUM END) AS TOTAL_SUM
FROM RESCORDS R
JOIN ACCOUNTS A ON R.ACC_REF = A.ID
JOIN PRODUCTS P ON A.PRODUCT_REF = P.ID
JOIN CLIENTS C ON P.CLIENT_REF = C.ID
WHERE R.OPER_DATE >= NOW() - INTERVAL '1 month'
GROUP BY CLIENT_NAME, R.OPER_DATE;


