UPDATE PRODUCTS p
SET CLOSE_DATE = CURRENT_DATE WHERE p.
PRODUCT_TYPE_ID = (SELECT ID FROM PRODUCT_TYPE WHERE NAME = 'КРЕДИТ')
AND p.CLOSE_DATE IS NULL
AND (
  SELECT SUM(CASE WHEN r.DT = 1 THEN r.SUM ELSE 0 END)
  FROM RECORDS r JOIN ACCOUNTS a ON r.ACC_REF = a.ID
  WHERE a.PRODUCT_REF = p.ID ) = ( 
  SELECT SUM(r.SUM)
  FROM RECORDS r JOIN ACCOUNTS a ON r.ACC_REF = a.ID
  WHERE a.PRODUCT_REF = p.ID
) 
AND NOT EXISTS ( 
  SELECT 1 FROM RECORDS r
  WHERE r.ACC_REF IN ( 
    SELECT ID FROM ACCOUNTS WHERE PRODUCT_REF = p.ID
) AND r.DT = 0
);


