UPDATE PRODUCT_TYPE 
SET END_DATE = CURRENT_DATE 
WHERE ID IN (
  SELECT p.PRODUCT_TYPE_ID
  FROM PRODUCTS p
  JOIN ACCOUNTS a ON p.ID = a.PRODUCT_REF 
  LEFT JOIN RECORDS r ON a.ID = r.ACC_REF
  WHERE (r.OPER_DATE IS NULL OR r.OPER_DATE < CURRENT_DATE - INTERVAL '1 MONTH') 
GROUP BY p.PRODUCT_TYPE_ID 
);


