CREATE TABLE CLIENTS ( 
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL, 
   PLACE_OF_BIRTH VARCHAR(100), 
   DATE_OF_BIRTH DATE,
   ADDRESS VARCHAR(255), 
   PASSPORT VARCHAR(20) UNIQUE NOT NULL 
);

CREATE TABLE PRODUCT_TYPE (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   BEGIN_DATE DATE NOT NULL, 
   END_DATE DATE,
   TARIF_REF INTEGER 
);

CREATE TABLE PRODUCTS ( 
   ID SERIAL PRIMARY KEY,
   PRODUCT_TYPE_ID INTEGER REFERENCES PRODUCT_TYPE(ID),
   NAME VARCHAR(255) NOT NULL,
   CLIENT_REF INTEGER REFERENCES CLIENTS(ID), 
   OPEN_DATE DATE NOT NULL,
   CLOSE_DATE DATE 
);

CREATE TABLE ACCOUNTS (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   SALDO DECIMAL(10, 2) DEFAULT 0,
   CLIENT_REF INT REFERENCES CLIENTS(ID),
   OPEN_DATE DATE,
   CLOSE_DATE DATE,
   PRODUCT_REF INT REFERENCES PRODUCTS(ID), 
   ACC_NUM VARCHAR(50) UNIQUE 
);

CREATE TABLE RECORDS (
   ID SERIAL PRIMARY KEY,
   DT BOOLEAN NOT NULL, -- 1 for debit, 0 for credit 
   ACC_REF INT REFERENCES ACCOUNTS(ID),
   OPER_DATE DATE,
   SUM DECIMAL(10, 2) NOT NULL
);

CREATE TABLE TARIFS (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   COST DECIMAL(10, 2) NOT NULL
);

ALTER TABLE PRODUCTS ADD COLUMN CONTRACT_AMOUNT DECIMAL(10, 2);
