CREATE TABLE CLIENTS ( 
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL, 
   PLACE_OF_BIRTH VARCHAR(100), 
   DATE_OF_BIRTH DATE,
   ADDRESS VARCHAR(255), 
   PASSPORT VARCHAR(20) 
   UNIQUE NOT NULL 
);

CREATE TABLE PRODUCT_TYPE (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   BEGIN_DATE DATE NOT NULL, 
   END_DATE DATE,
   TARIF_REF INTEGER 
);

CREATE TABLE PRODUCTS ( 
   ID SERIAL PRIMARY KEY,
   PRODUCT_TYPE_ID INTEGER REFERENCES PRODUCT_TYPE(ID),
   NAME VARCHAR(255) NOT NULL,
   CLIENT_REF INTEGER REFERENCES CLIENTS(ID), 
   OPEN_DATE DATE NOT NULL,
   CLOSE_DATE DATE 
);
