WITH MaxDebit AS (
  SELECT p.ID AS PRODUCT_ID, MAX(r.SUM) AS MAX_SUM
  FROM PRODUCTS p 
  JOIN ACCOUNTS a ON p.ID = a.PRODUCT_REF
  JOIN RECORDS r ON a.ID = r.ACC_REF
  WHERE p.PRODUCT_TYPE_ID = (
    SELECT ID FROM PRODUCT_TYPE WHERE NAME = 'КРЕДИТ') 
AND r.DT = TRUE 
GROUP BY p.ID 
), 
MaxCredit AS (
  SELECT p.ID AS PRODUCT_ID, MAX(r.SUM) AS MAX_SUM 
  FROM PRODUCTS p 
  JOIN ACCOUNTS a ON p.ID = a.PRODUCT_REF
  JOIN RECORDS r ON a.ID = r.ACC_REF
  WHERE p.PRODUCT_TYPE_ID IN (
    SELECT ID FROM PRODUCT_TYPE WHERE NAME IN ('ДЕПОЗИТ', 'КАРТА'))
  AND r.DT = FALSE
  GROUP BY p.ID
)
UPDATE PRODUCTS 
SET SUM_CONTRACT = COALESCE((SELECT MD.MAX_SUM FROM MaxDebit MD WHERE MD.PRODUCT_ID = PRODUCTS.ID),
                            (SELECT MC.MAX_SUM FROM MaxCredit MC WHERE MC.PRODUCT_ID = PRODUCTS.ID));
